name: Build & Push

"on":
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Get tag
        id: repository
        run: echo  "::set-output name=tag::$(git describe --tags HEAD)"

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: registry.eq.gy/library/wp-phpfpm-redis
          username: ${{ secrets.REGISTRY_USER}}
          password: ${{ secrets.REGISTRY_PASS }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: registry.eq.gy/library/wp-phpfpm-redis:${{ steps.repository.outputs.tag }}
